# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 350))
        MainWindow.setMaximumSize(QtCore.QSize(600, 350))
        MainWindow.setBaseSize(QtCore.QSize(600, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 550))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 43))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.DisplayRomName = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DisplayRomName.sizePolicy().hasHeightForWidth())
        self.DisplayRomName.setSizePolicy(sizePolicy)
        self.DisplayRomName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.DisplayRomName.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DisplayRomName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DisplayRomName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.DisplayRomName.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.DisplayRomName.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.DisplayRomName.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.DisplayRomName.setObjectName("DisplayRomName")
        self.gridLayout.addWidget(self.DisplayRomName, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(4, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.OpenRom = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenRom.sizePolicy().hasHeightForWidth())
        self.OpenRom.setSizePolicy(sizePolicy)
        self.OpenRom.setObjectName("OpenRom")
        self.gridLayout.addWidget(self.OpenRom, 1, 5, 1, 1, QtCore.Qt.AlignVCenter)
        self.File_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File_label.sizePolicy().hasHeightForWidth())
        self.File_label.setSizePolicy(sizePolicy)
        self.File_label.setMinimumSize(QtCore.QSize(0, 10))
        self.File_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.File_label.setObjectName("File_label")
        self.gridLayout.addWidget(self.File_label, 1, 1, 1, 1, QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 30, 581, 35))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.I_TNESInfo = QtWidgets.QLabel(self.centralwidget)
        self.I_TNESInfo.setGeometry(QtCore.QRect(40, 54, 71, 17))
        self.I_TNESInfo.setObjectName("I_TNESInfo")
        self.I_FDSInfo = QtWidgets.QLabel(self.centralwidget)
        self.I_FDSInfo.setGeometry(QtCore.QRect(320, 54, 67, 17))
        self.I_FDSInfo.setObjectName("I_FDSInfo")
        self.TNESInfo = QtWidgets.QFrame(self.centralwidget)
        self.TNESInfo.setGeometry(QtCore.QRect(30, 70, 251, 251))
        self.TNESInfo.setFrameShape(QtWidgets.QFrame.Box)
        self.TNESInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TNESInfo.setLineWidth(1)
        self.TNESInfo.setMidLineWidth(2)
        self.TNESInfo.setObjectName("TNESInfo")
        self.PRGROMSize_L = QtWidgets.QLabel(self.TNESInfo)
        self.PRGROMSize_L.setGeometry(QtCore.QRect(10, 40, 101, 17))
        self.PRGROMSize_L.setObjectName("PRGROMSize_L")
        self.Mapper_L = QtWidgets.QLabel(self.TNESInfo)
        self.Mapper_L.setGeometry(QtCore.QRect(10, 10, 67, 20))
        self.Mapper_L.setObjectName("Mapper_L")
        self.CHRROMSize_L = QtWidgets.QLabel(self.TNESInfo)
        self.CHRROMSize_L.setGeometry(QtCore.QRect(10, 100, 101, 17))
        self.CHRROMSize_L.setObjectName("CHRROMSize_L")
        self.PRGROMCRC_L = QtWidgets.QLabel(self.TNESInfo)
        self.PRGROMCRC_L.setGeometry(QtCore.QRect(10, 70, 121, 17))
        self.PRGROMCRC_L.setObjectName("PRGROMCRC_L")
        self.Battery_C = QtWidgets.QLabel(self.TNESInfo)
        self.Battery_C.setGeometry(QtCore.QRect(80, 220, 71, 17))
        self.Battery_C.setObjectName("Battery_C")
        self.PRGROMCRC_C = QtWidgets.QLabel(self.TNESInfo)
        self.PRGROMCRC_C.setGeometry(QtCore.QRect(140, 70, 91, 17))
        self.PRGROMCRC_C.setObjectName("PRGROMCRC_C")
        self.WRAM_C = QtWidgets.QLabel(self.TNESInfo)
        self.WRAM_C.setGeometry(QtCore.QRect(70, 160, 71, 17))
        self.WRAM_C.setObjectName("WRAM_C")
        self.CHRROMCRC_C = QtWidgets.QLabel(self.TNESInfo)
        self.CHRROMCRC_C.setGeometry(QtCore.QRect(140, 130, 81, 17))
        self.CHRROMCRC_C.setObjectName("CHRROMCRC_C")
        self.CHRROMSize_C = QtWidgets.QLabel(self.TNESInfo)
        self.CHRROMSize_C.setGeometry(QtCore.QRect(120, 100, 101, 17))
        self.CHRROMSize_C.setObjectName("CHRROMSize_C")
        self.Mirroring_C = QtWidgets.QLabel(self.TNESInfo)
        self.Mirroring_C.setGeometry(QtCore.QRect(90, 190, 151, 17))
        self.Mirroring_C.setObjectName("Mirroring_C")
        self.Mapper_C = QtWidgets.QLabel(self.TNESInfo)
        self.Mapper_C.setGeometry(QtCore.QRect(80, 10, 71, 20))
        self.Mapper_C.setObjectName("Mapper_C")
        self.PRGROMSize_C = QtWidgets.QLabel(self.TNESInfo)
        self.PRGROMSize_C.setGeometry(QtCore.QRect(120, 40, 111, 17))
        self.PRGROMSize_C.setObjectName("PRGROMSize_C")
        self.CHRROMCRC_L = QtWidgets.QLabel(self.TNESInfo)
        self.CHRROMCRC_L.setGeometry(QtCore.QRect(10, 130, 121, 17))
        self.CHRROMCRC_L.setObjectName("CHRROMCRC_L")
        self.WRAM_L = QtWidgets.QLabel(self.TNESInfo)
        self.WRAM_L.setGeometry(QtCore.QRect(10, 160, 67, 17))
        self.WRAM_L.setObjectName("WRAM_L")
        self.Mirroring_L = QtWidgets.QLabel(self.TNESInfo)
        self.Mirroring_L.setGeometry(QtCore.QRect(10, 190, 67, 17))
        self.Mirroring_L.setObjectName("Mirroring_L")
        self.Battery_L = QtWidgets.QLabel(self.TNESInfo)
        self.Battery_L.setGeometry(QtCore.QRect(10, 220, 61, 17))
        self.Battery_L.setObjectName("Battery_L")
        self.FDSInfo = QtWidgets.QFrame(self.centralwidget)
        self.FDSInfo.setGeometry(QtCore.QRect(300, 70, 261, 101))
        self.FDSInfo.setFrameShape(QtWidgets.QFrame.Box)
        self.FDSInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FDSInfo.setLineWidth(1)
        self.FDSInfo.setMidLineWidth(2)
        self.FDSInfo.setObjectName("FDSInfo")
        self.FDSDiskCount_C = QtWidgets.QLabel(self.FDSInfo)
        self.FDSDiskCount_C.setGeometry(QtCore.QRect(100, 40, 51, 17))
        self.FDSDiskCount_C.setObjectName("FDSDiskCount_C")
        self.FDSDiskCount_L = QtWidgets.QLabel(self.FDSInfo)
        self.FDSDiskCount_L.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.FDSDiskCount_L.setObjectName("FDSDiskCount_L")
        self.FDSBIOSCRC_C = QtWidgets.QLabel(self.FDSInfo)
        self.FDSBIOSCRC_C.setGeometry(QtCore.QRect(140, 10, 91, 17))
        self.FDSBIOSCRC_C.setObjectName("FDSBIOSCRC_C")
        self.FDSBIOSCRC_L = QtWidgets.QLabel(self.FDSInfo)
        self.FDSBIOSCRC_L.setGeometry(QtCore.QRect(10, 10, 121, 17))
        self.FDSBIOSCRC_L.setObjectName("FDSBIOSCRC_L")
        self.FDSSidesPerDisk_L = QtWidgets.QLabel(self.FDSInfo)
        self.FDSSidesPerDisk_L.setGeometry(QtCore.QRect(10, 70, 101, 17))
        self.FDSSidesPerDisk_L.setObjectName("FDSSidesPerDisk_L")
        self.FDSSidesPerDisk_C = QtWidgets.QLabel(self.FDSInfo)
        self.FDSSidesPerDisk_C.setGeometry(QtCore.QRect(120, 70, 51, 17))
        self.FDSSidesPerDisk_C.setObjectName("FDSSidesPerDisk_C")
        self.Buttons = QtWidgets.QWidget(self.centralwidget)
        self.Buttons.setGeometry(QtCore.QRect(300, 210, 261, 91))
        self.Buttons.setObjectName("Buttons")
        self.TNEStoINES = QtWidgets.QPushButton(self.Buttons)
        self.TNEStoINES.setGeometry(QtCore.QRect(10, 0, 111, 25))
        self.TNEStoINES.setObjectName("TNEStoINES")
        self.ExtractQD = QtWidgets.QPushButton(self.Buttons)
        self.ExtractQD.setGeometry(QtCore.QRect(140, 0, 111, 25))
        self.ExtractQD.setObjectName("ExtractQD")
        self.ExtractPRG = QtWidgets.QPushButton(self.Buttons)
        self.ExtractPRG.setGeometry(QtCore.QRect(10, 30, 111, 25))
        self.ExtractPRG.setObjectName("ExtractPRG")
        self.ExtractCHR = QtWidgets.QPushButton(self.Buttons)
        self.ExtractCHR.setGeometry(QtCore.QRect(140, 30, 111, 25))
        self.ExtractCHR.setObjectName("ExtractCHR")
        self.ExtractFDSBIOS = QtWidgets.QPushButton(self.Buttons)
        self.ExtractFDSBIOS.setGeometry(QtCore.QRect(70, 60, 121, 25))
        self.ExtractFDSBIOS.setObjectName("ExtractFDSBIOS")
        self.FDSInfo.raise_()
        self.gridLayoutWidget.raise_()
        self.line.raise_()
        self.I_FDSInfo.raise_()
        self.TNESInfo.raise_()
        self.I_TNESInfo.raise_()
        self.Buttons.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenRom = QtWidgets.QAction(MainWindow)
        self.actionOpenRom.setObjectName("actionOpenRom")
        self.actionClearRom = QtWidgets.QAction(MainWindow)
        self.actionClearRom.setObjectName("actionClearRom")
        self.actionExitProgram = QtWidgets.QAction(MainWindow)
        self.actionExitProgram.setObjectName("actionExitProgram")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tnes 2 Ines GUI"))
        self.DisplayRomName.setPlaceholderText(_translate("MainWindow", "TNES rom file..."))
        self.OpenRom.setText(_translate("MainWindow", "Open"))
        self.File_label.setText(_translate("MainWindow", "File:"))
        self.I_TNESInfo.setText(_translate("MainWindow", "TNES info"))
        self.I_FDSInfo.setText(_translate("MainWindow", "FDS Info"))
        self.PRGROMSize_L.setText(_translate("MainWindow", "PRG ROM size:"))
        self.Mapper_L.setText(_translate("MainWindow", "Mapper:"))
        self.CHRROMSize_L.setText(_translate("MainWindow", "CHR ROM size:"))
        self.PRGROMCRC_L.setText(_translate("MainWindow", "PRG ROM CRC32:"))
        self.Battery_C.setText(_translate("MainWindow", "N/A"))
        self.PRGROMCRC_C.setText(_translate("MainWindow", "N/A"))
        self.WRAM_C.setText(_translate("MainWindow", "N/A"))
        self.CHRROMCRC_C.setText(_translate("MainWindow", "N/A"))
        self.CHRROMSize_C.setText(_translate("MainWindow", "N/A"))
        self.Mirroring_C.setText(_translate("MainWindow", "N/A"))
        self.Mapper_C.setText(_translate("MainWindow", "N/A"))
        self.PRGROMSize_C.setText(_translate("MainWindow", "N/A"))
        self.CHRROMCRC_L.setText(_translate("MainWindow", "CHR ROM CRC32:"))
        self.WRAM_L.setText(_translate("MainWindow", "WRAM:"))
        self.Mirroring_L.setText(_translate("MainWindow", "Mirroring:"))
        self.Battery_L.setText(_translate("MainWindow", "Battery:"))
        self.FDSDiskCount_C.setText(_translate("MainWindow", "N/A"))
        self.FDSDiskCount_L.setText(_translate("MainWindow", "Disk Count:"))
        self.FDSBIOSCRC_C.setText(_translate("MainWindow", "N/A"))
        self.FDSBIOSCRC_L.setText(_translate("MainWindow", "FDS BIOS CRC32:"))
        self.FDSSidesPerDisk_L.setText(_translate("MainWindow", "Sides per Disk:"))
        self.FDSSidesPerDisk_C.setText(_translate("MainWindow", "N/A"))
        self.TNEStoINES.setText(_translate("MainWindow", "Convert to INES"))
        self.ExtractQD.setText(_translate("MainWindow", "Extract FDS QD"))
        self.ExtractPRG.setText(_translate("MainWindow", "Extract PRG"))
        self.ExtractCHR.setText(_translate("MainWindow", "Extract CHR"))
        self.ExtractFDSBIOS.setText(_translate("MainWindow", "Extract FDS BIOS"))
        self.actionOpenRom.setText(_translate("MainWindow", "Open"))
        self.actionClearRom.setText(_translate("MainWindow", "Close"))
        self.actionExitProgram.setText(_translate("MainWindow", "Exit"))
